use_frameworks!

target 'react-native-firestack_Example' do
  pod 'react-native-firestack', :path => '../'

  target 'react-native-firestack_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
