# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sample
  pod "react-native-firestack", :path => "../.."

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
