source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# frameworks = Dir.glob("./Pods/**/*.framework").map {|d| d.gsub(/\.\/Pods\//, '$(PROJECT_DIR)/Pods/')}
# flat_frameworks = frameworks.flatten.map{|i| "\"#{i}\""}.join(' ')

def common_specs
  pod 'Firestack', :path => '../'
  pod 'React', :path => '../node_modules/react-native'
   # [
   #   'Firebase/Core',
   #   'Firebase/Auth',
   #   'Firebase/Storage',
   #   'Firebase/Database',
   #   'Firebase/RemoteConfig'
   # ].each do |lib|
   #   pod lib
   # end
end

target 'Firestack' do
  use_frameworks!
  common_specs

  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |configuration|
  #       # target.build_settings(configuration.name)['FRAMEWORK_SEARCH_PATHS'] = flat_frameworks
  #       # target.build_settings(configuration.name)['USER_HEADER_SEARCH_PATHS'] = "$(BUILT_PRODUCTS_DIR)"
  #       target.build_settings(configuration.name)['HEADER_SEARCH_PATHS'] = [
  #         "$(inherited)", "${PODS_ROOT}/Headers/**",
  #         "$(SRCROOT)/../../../React/**",
  #         "$(SRCROOT)/../../../react-native/React/**"
  #       ].join(' ')
  #       # target.build_settings(configuration.name)['OTHER_LDFLAGS'] = "$(inherited) -undefined dynamic_lookup"
  #     end
  #   end
  # end
end
