# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Firestack' do
  use_frameworks!

  [
    'Firebase/Core',
    'Firebase/Auth',
    'Firebase/Storage',
    'Firebase/Database'
  ].each do |lib|
    pod lib
  end

end
